### ISSUE TITLE
Lack of HOLZ: warning message

### ISSUE THREAD

**Issue by AJMHubert** [RudoRoemer/Felix#114]
in diffractionpatterndefinitions.f90, Line 175:

```
    IF((RgVecMatT(ind,3).GT.TINY.OR.RgVecMatT(ind,3).LT.-TINY).AND.ICutOff.NE.0) THEN
       RGzUnitVec=ABS(RgVecMatT(ind,3))
       ICutOff=0
    END IF
```

 ENDDO

```
 !No higher order Laue Zones with ZOLZFlag switched on
 IF(ICutOff.EQ.1) THEN
    RGzUnitVec=ZERO
 END IF
 CALL Message("ReflectionDetermination", IMoreInfo,IErr, &
            MessageVariable="RGzUnitVec", &
            RVariable=RGzUnitVec)
```

If ZolzFlag is set to 0 (ie the user wants Holz) but there are not enough reflections in the reflection pool to accommodate HOLZ reflections, felix should probably output a message saying so.

2 minute job - just putting on here to make sure I don't forget about it

**Comment by RudoRoemer** [comment]
has this now been done?

**Comment by JacobJoseph-gu** [comment]
I think I can see the issue and it is still there, i've now added an error message using l_alert()
The following is core 1 printing the minor error

 "1 = rank, error in felixrefine after attempting to fill Laue Zones. IHolzFLAG = 1 in felix.inp, however no higher order g-vectors were found. Continuing with zero order Laue zone only."

**Comment by rbeanland** [comment]
The ZOLZ/HOLZ issue is unclear at the moment to me and probably a bit of a mess. Current issues include:
1) There is a key difference in the physics; ZOLZ diffraction can (more or less) get away with a small angle approximation, which is definitely not the case for HOLZ.  I think we should probably just use the accurate calculation since the time penalty in a numerical calculation is small in comparison with matrix diagonalisation and absorption calculations. However I seem to remember that it adds a big time penalty to the calculation so maybe there is some detail I have forgotten. 
2) There is a lump of code currently sitting in felixrefine.f90 that may sort reflections into Laue zones, but I am not sure how well it works beyond identifying ZOLZ reflections. I don't know if it considers negative Laue zones or how it takes account of the microscope acceptance angle.
