### ISSUE TITLE
Output issues for Felixsim

### ISSUE THREAD

**Issue by AJMHubert** [RudoRoemer/Felix#122]
For some reason, the output image name is copying itself over and over again, possibly because of my inclusion of a loop over varying thicknesses. The issue is in WriteIterationOutput Lines 49 to 90. It is an issue to do with the variable 'filename'. 

A repetition in filename causes an overwriting of data. As soon as I fix this Felixsim may well be functional again.

**Comment by rbeanland** [comment]
Hi Alex,
Make the loop calling the image writing code start before the directory path is set. This way, output for each thickness will go into a separate folder as created by mkdir.

Richard

On 27 Sep 2016, at 16:14, Alex Hubert <notifications@github.com<mailto:notifications@github.com>> wrote:


For some reason, the output image name is copying itself over and over again, possibly because of my inclusion of a loop over varying thicknesses. The issue is in WriteIterationOutput Lines 49 to 90. It is an issue to do with the variable 'filename'.

A repetition in filename causes an overwriting of data. As soon as I fix this Felixsim may well be functional again.

-

**Comment by AJMHubert** [comment]
Thanks Richard, It is semi-fixed. Good news is it seems felixsim is working again! At least for the one input file anyway. Closing Issue
