### ISSUE TITLE
reenabling felxsim

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#125]
when recompiling felixsim in the new master branch and running for GaAs as in samples, I get

phsht@ThinkPad-X1:~/Projects/D-LACBED/Felix/samples/GaAs$ ../../src/felixsim 

---

 felixsim: Version :RB_input:, Build :1: 
           Date :5 October 2016:  
           Status :in test:, Author :Richard+Alex: 
           on rank=            0  of            1  in total.

---

At line 57 of file inputmodules.f90
Fortran runtime error: End of file

Why?

**Comment by rbeanland** [comment]
This is because the input file has changed. The version below should work.


Richard


# Input file for Felix version :VERSION: Build :BUILD:
# ------------------------------------

# ------------------------------------

# control flags
IWriteFLAG                = 4
IImageFLAG                = 10
IScatterFactorMethodFLAG  = 0
IMaskFLAG                 = 1
IHolzFLAG                 = 0
IAbsorbFLAG               = 2
IAnisoDebyeWallerFlag     = 0
IByteSize                 = 8

# radius of the beam in pixels
IPixelCount               = 64

# beam selection criteria
IMinReflectionPool        = 160
IMinStrongBeams           = 30
IMinWeakBeams             = 30

# crystal settings
RDebyeWallerConstant      = 0.54
RAbsorptionPer            = 7.8

# microscope settings
ROuterConvergenceAngle    = 3.35
IIncidentBeamDirection    = [0,0,1]
IXDirection               = [1,1,0]
INormalDirection          = [0,0,1]
RAcceleratingVoltage (kV) = 200.0
RAcceptanceAngle          = 0.0

# Image Output Options
RInitialThickness        = 1400.0
RFinalThickness          = 1500.0
RDeltaThickness          = 10.0
IReflectOut              = 1

#Refinement Specific Flags
IRefineModeFLAG          = D
IWeightingFLAG           = 0
IContinueFLAG            = 0
ICorrelationFLAG         = 3
IImageProcessingFLAG     = 4
RBlurRadius              = 0.01
INoofUgs                 = 1
IAtomicSites             = (1,2)
IPrint                   = 4
RSimplexLengthScale      = 5.0
RExitCriteria            = 0.00001


On 7 Oct 2016, at 19:59, Rudolf A Roemer <notifications@github.com<mailto:notifications@github.com>> wrote:


when recompiling felixsim in the new master branch and running for GaAs as in samples, I get

phsht@ThinkPad-X1:~/Projects/D-LACBED/Felix/samples/GaAs$ ../../src/felixsim

________________________________

felixsim: Version :RB_input:, Build :1:
Date :5 October 2016:

Status :in test:, Author :Richard+Alex:
on rank= 0 of 1 in total.

________________________________

At line 57 of file inputmodules.f90
Fortran runtime error: End of file

Why?

-

**Comment by AJMHubert** [comment]
"IRefineModeFLAG          = S" - I've been updating the User guide too (still a work in progress)

 run ../../src/felixrefine

felixrefine and felixsim have been combined now

**Comment by RudoRoemer** [comment]
new branch "cleanup", with felix.inp in GaAs. Output shows error. So felixsim does not work nor does felixrefine with "IRefineModeFLAG           = S".

 --------------------------------------------------------------
 felixrefine: Version: VERSION / BUILD / RLS
              Date: DATE / TIME             
              Status: AUTHOR                          
     on rank=            0  of            1  in total.
 --------------------------------------------------------------
 MeanInnerPotential= 15.32  Volts
 90 unique structure factors
 Absorption completed in   0 hrs  0 mins  6 sec
 Bloch wave calculation...
 Simulation completed in   0 hrs  1 mins 52 sec
 Writing simulations for           11 thicknesses
 Exiting and writing output; 
At line 75 of file RefineWriteOut.f90
Fortran runtime error: Index '1' of dimension 1 of array 'ioutputreflections' above upper bound of 0
phsht@ThinkPad-X1:~/Projects/D-LACBED/Felix/samples/GaAs$

**Comment by rbeanland** [comment]
I don't know the source of the error, but is there a Felix.hkl file that lists the output reflections? I can imagine this could give a bug like this.

Richard

On 7 Oct 2016, at 21:40, Rudolf A Roemer <notifications@github.com<mailto:notifications@github.com>> wrote:


new branch "cleanup", with felix.inp in GaAs. Output shows error. So felixsim does not work nor does felixrefine with "IRefineModeFLAG = S".

________________________________

felixrefine: Version: VERSION / BUILD / RLS
Date: DATE / TIME

Status: AUTHOR

on rank= 0 of 1 in total.

________________________________

MeanInnerPotential= 15.32 Volts
90 unique structure factors
Absorption completed in 0 hrs 0 mins 6 sec
Bloch wave calculation...
Simulation completed in 0 hrs 1 mins 52 sec
Writing simulations for 11 thicknesses
Exiting and writing output;
At line 75 of file RefineWriteOut.f90
Fortran runtime error: Index '1' of dimension 1 of array 'ioutputreflections' above upper bound of 0
phsht@ThinkPad-X1:~/Projects/D-LACBED/Felix/samples/GaAs$

-

**Comment by kidwhizz** [comment]
unless you're changed it, FelixRefine assumes Felix.hkl exists because said file simultaneously tells Felix what reflections are being input and what to output, if IOutputReflections is of 0 size, then its either empty or not being read correctly (or at all)
