### ISSUE TITLE
rainbow-intensity images using command-line convert

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#168]
I thought I'd share this here:

convert -size 070x070 -depth 64 -define quantum:format=floating-point -define quantum:scale=65535.0 -endian lsb GRAY:GaAs_085nm_070x070_+0+0+0.bin GaAs_085nm_070x070_+0+0+0.png

![gaas_085nm_070x070_ 0 0 0](https://user-images.githubusercontent.com/23014872/29408245-5aea325a-833f-11e7-94d5-0fa8090f4667.png)

convert xc:black xc:red xc:orange xc:yellow xc:green1 xc:cyan xc:blue xc:blueviolet xc:black +append -filter Cubic -resize 600x30! -flop rainbow.png

![rainbow](https://user-images.githubusercontent.com/23014872/29408264-685e3742-833f-11e7-95f3-6fe940167047.png)

convert GaAs_085nm_070x070_+0+0+0.png -colorspace gray rainbow.png -clut GaAs_085nm_070x070_+0+0+0_rainbow.png

![gaas_085nm_070x070_ 0 0 0_rainbow](https://user-images.githubusercontent.com/23014872/29408272-723d61ac-833f-11e7-809b-c61ddbbb5be2.png)

**Comment by RudoRoemer** [comment]
Good, but not quite “Carling” ;-)

The rainbow colours at high intensities should not go back to black, but best end in “white” (or some colour clearly different from black). Otherwise the no-intensity is hard to distinguish from the max-intensity.

With my best regards,
—
Rudolf A. Roemer
Department of Physics, University of Warwick, Coventry, CV4 7AL, UK www.warwick.ac.uk/go/rudoroemer, +44 7984 353749

**Comment by JacobJoseph-gu** [comment]
It is a bad habbit of mine to move on once I have worked out how to do something, instead of finishing it off.

By using creating the 600x30 rainbow image, we easily have full control and can play around with various looks:

![rainbow 1](https://user-images.githubusercontent.com/23014872/29410651-689b77f6-8349-11e7-97f1-e55813f00e3a.png)

![crystal_rainbow](https://user-images.githubusercontent.com/23014872/29410653-69ebeab4-8349-11e7-860b-26a3a83e7e54.png)
